name: Build and execute integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_integration_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore
    - name: Build application
      run: dotnet build --no-restore
    - name: Execute integration tests
      run: dotnet test Homes.IntegrationTests/Homes.IntegrationTests.csproj --no-build --verbosity normal
